/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20TransferWithAuthorization,
  IERC20TransferWithAuthorizationInterface,
} from "../../../contracts/ZIP0PaymentVault.sol/IERC20TransferWithAuthorization";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "authorizer",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "nonce",
        type: "bytes32",
      },
    ],
    name: "authorizationState",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "validAfter",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "validBefore",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "nonce",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "transferWithAuthorization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20TransferWithAuthorization__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20TransferWithAuthorizationInterface {
    return new Interface(_abi) as IERC20TransferWithAuthorizationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20TransferWithAuthorization {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC20TransferWithAuthorization;
  }
}
