/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRefundableVault,
  IRefundableVaultInterface,
} from "../../../../contracts/test/ReentrantRefundToken.sol/IRefundableVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
    ],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "destinationDomain",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "destinationRecipient",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
    ],
    name: "depositPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRefundableVault__factory {
  static readonly abi = _abi;
  static createInterface(): IRefundableVaultInterface {
    return new Interface(_abi) as IRefundableVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRefundableVault {
    return new Contract(address, _abi, runner) as unknown as IRefundableVault;
  }
}
