/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zip0PaymentVaultSol from "./ZIP0PaymentVault.sol";
export type { zip0PaymentVaultSol };
import type * as test from "./test";
export type { test };
