/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20TransferWithAuthorization } from "./IERC20TransferWithAuthorization";
export type { ZIP0PaymentVault } from "./ZIP0PaymentVault";
